name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest bandit

      - name: Run Tests
        run: pytest

      - name: Run Bandit Security Scan
        run: bandit -r app/